# Generated by Django 4.1.5 on 2023-01-26 14:03

from decimal import Decimal
from django.conf import settings
import django.contrib.postgres.fields.citext
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django.contrib.postgres.fields.citext.CICharField(max_length=128)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('amount', models.PositiveIntegerField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='shops.shop')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'weight', 'shop_id')},
            },
        ),
        migrations.CreateModel(
            name='ReservedUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_units', to='units.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'unit_id')},
            },
        ),
    ]
