# Generated by Django 4.1.5 on 2023-02-03 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservedunit',
            options={'ordering': ['unit__shop__name', 'unit__name', 'unit__price']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['shop__name', 'name', 'price']},
        ),
        migrations.AlterField(
            model_name='reservedunit',
            name='amount',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='unit',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
