# Generated by Django 4.1.5 on 2023-02-08 16:04

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_alter_reservedunit_options_alter_unit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='unit',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
