# Generated by Django 4.1.5 on 2023-02-06 08:36

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=128, unique=True),
        ),
    ]
